---
title: "causalNMF"
author: "Lucas Gillenwater"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = "~/OneDrive - The University of Colorado Denver/Projects/causalNMF/")
```



# Data
```{r}
## counts pre=processing, only run once.

# counts <- read.delim("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/HTP_data/HTP_WholeBlood_RNAseq_Counts_Synapse.txt")
# 
# load("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/processed/processed_transcriptome.RData")
# 
# htp_expr <- counts %>%
#     filter(Gene_name %in% names(expression_list$expression)) %>%
#     dplyr::select(LabID, Gene_name,Value) %>%
#     distinct(LabID, Gene_name, .keep_all = T) %>%
#     pivot_wider(names_from = Gene_name, id_cols = LabID, values_from = Value) %>%
#     column_to_rownames("LabID")
# 
# save(htp_expr, file = "~/OneDrive - The University of Colorado Denver/Projects/causalNMF/data/htp_expression_counts_prot_variance_filtered.RData")

```

```{r}

library(tidyverse)

source("functions.R")

load( "~/OneDrive - The University of Colorado Denver/Projects/causalNMF/data/htp_expression_counts_prot_variance_filtered.RData")

comorbid_long <- read.delim("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/HTP_data/P4C_Comorbidity_020921.tsv", skip = 1)

comorbid_wide <- comorbid_long %>%
#  mutate(HasCondition = as.factor(HasCondition)) %>%
  pivot_wider(names_from = Condition, values_from = HasCondition, id_cols = RecordID)

metadata <- read.delim("~/OneDrive - The University of Colorado Denver/Projects/ImmunoMetabolicSubtypes/data/HTP_data/P4C_metadata_021921_Costello.txt")

metadata <- metadata %>%
  left_join(comorbid_wide, by = "RecordID")

dim(metadata)

metadata <- metadata %>%
  mutate(karyotype_binary =ifelse(Karyotype == "T21",1,0))

# metadata <- metadata %>%
#   mutate(
#     across(unique(comorbid_long$Condition), ~replace_na(.x,as.factor(0))))

metadata <- metadata %>%
  tibble(.name_repair = "universal")

# create metavariable for features with counts > 

#summary(metadata)

# metadata <- metadata %>%
#   mutate(condition = interaction(metadata$Any.autoimmune.skin.condition,
#                                  metadata$Any.hypothyroidism))
# 

metadata <- metadata %>%
  filter(LabID %in% rownames(htp_expr)) 

htp_expr <- htp_expr %>%
  filter(rownames(htp_expr) %in% metadata$LabID)


metadata <- metadata[match(rownames(htp_expr),metadata$LabID),]

identical(rownames(htp_expr), metadata$LabID)


```


# Running the model

```{r}
Y = htp_expr[,1:1000]
exposure = "karyotype_binary"
condition = "Obesity"
metadata = metadata
iterations = 50
lv_num = 20
learning_rate = .001
alpha = .5



```

```{r}
source("functions.R")

results <- causalNMF(Y = Y,
          exposure = exposure,
          condition = condition,
          metadata = metadata,
          diff_threshold = 1e-4,
          percent_threshold = .7, 
          beta = 1,
          lambda = 1)


```

```{r}
plot(results$error)
plot(results$H_diff)
```

```{r}
library(igraph)

g <- graph_from_adjacency_matrix(results$causal_graph,weighted = TRUE)

nodes_with_edges <- V(g)[degree(g) >0]

subgraph <- induced_subgraph(g,nodes_with_edges)
plot(subgraph,layout = layout_in_circle)
```



```{r}
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(ggbeeswarm)

mediators <- results$causal_lvs

for(i in mediators) {
  
  C <- metadata %>%
    filter(LabID %in% rownames(results$W))
  # Create a data frame
  data <- data.frame(independent = C$karyotype_binary, mediator = results$W[,i], dependent = C$Obesity)
  
  data$mediator <- scale(data$mediator)
  
   
  # Plot

  
  p2 <- ggplot(data, aes(x = factor(dependent), y = mediator, color = factor(independent))) +
    geom_boxplot( alpha = .5)+
    geom_quasirandom()+
    stat_compare_means(method = "wilcox.test", label = "p.format", 
                       comparisons = list(c("0","1")))+
    labs(title = "Stratified By Karyotype",
         y = paste0("LV",i),
         x = "Condition",
         color = "T21")+
     facet_wrap(~factor(independent)) +
    theme_classic()
  
  
  p1 <- ggplot(data, aes(x = factor(dependent), y = mediator)) +
    geom_boxplot(alpha = .5, outlier.shape =  NA)+
    geom_jitter()+
      stat_compare_means(method = "wilcox.test", label = "p.format")+
    labs(tile = "Full Cohort",
         y = paste0("LV",i),
         x = "Condition",
         color = "T21") +
    theme_classic()
  
  
  grid.arrange(p1,p2, ncol = 2, top = paste0("LV",i), widths = c(1,2))
}

```
